version: "3"
services: 

  go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://172.24.2.10:8080
        - https_proxy=http://172.24.2.10:8080
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:  
      - "8888:8080"
  
  